# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_dispatch:
#  push:
#    branches: [main, master]
#  pull_request:
#    branches: [main, master]

name: R-CMD-check-complete

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} (${{ matrix.r }})

    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macOS-latest' ]
        r: [ 'devel', 'release', 'oldrel-1', '4.3.3', '4.2.3', '4.1.3', '4.0.5' ]
        include:
          - http-user-agent: 'release'
            r: 'devel'

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      DISPLAY: ':99.0'

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-tinytex@v2

      # Some additionnal set up for clipr in ubuntu
      - name: Install and run XVFB
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          sudo /usr/bin/Xvfb :99.0 -screen 0 1280x1024x24 &
          sleep 3

      - name: Installation de xclip pour clipr
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y xclip
          # Initialize xclip
          uptime | xclip -i -sel p -f | xclip -i -sel c
          xclip -o -sel clipboard

      - name: Installation de libpoppler pour pdftools pour Linux
        if: runner.os == 'macOS'
        run: sudo apt-get install libpoppler-cpp-dev

      - name: Installation de libpoppler pour pdftools pour MacOS
        if: runner.os == 'macOS'
        run: brew install poppler

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}
          http-user-agent: ${{ matrix.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
